nk_social_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    re_path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

posts/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.HopePage.as_view(), name="index"),
    path("following/", views.FollowingView.as_view(), name="following"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"

urlpatterns = [
    path("<str:username>", views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow", views.FollowView.as_view(), name="follow"),
    path("<str:username>/edit", views.EditProfile.as_view(), name="edit"),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# from sorl.thumbnail import ImageField
from cloudinary.models import CloudinaryField

# Create your models here.
class Profile(models.Model) : 
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        # related_name = 'profile'
    )
    image = CloudinaryField('image')
    backdrop_image = CloudinaryField('backdrop_image')
    
    def __str__(self) : 
        return f'{self.user.username} {self.user.last_name}'
    
@receiver(post_save, sender=User)
def create_user_profile (sender, instance, created, **kwargs) : 
    """Create a new Profile() object whenever a django user is created"""
    if created: 
        Profile.objects.create(user=instance)

profiles/views.py
from typing import Any
from django.contrib.auth.models import User
from django.views.generic import DetailView, View, CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse
from posts.models import Post
from django.shortcuts import render
from followers.models import Followers
from .models import Profile
from nk_social_app.settings import logger

class ProfileDetailView( DetailView ):
    http_method_names = ["get"]
    template_name = "profiles/details.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"
    
    def dispatch(self, request, *args, **kwargs) :
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context["total_posts"] = Post.objects.filter(author=user).count()
        context["total_followers"] = Followers.objects.filter(following__username=user.username).count()
        context["total_following"] = Followers.objects.filter(followed_by__username=user.username).count()
        if self.request.user.is_authenticated:
            context["check_follow"] = Followers.objects.filter(following=user, followed_by=self.request.user).exists()
        return context
    
class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]
    
    def post(self, request, *args, **kwargs):
        data = request.POST.dict()
        
        if "username" not in data or "action" not in data:
            return HttpResponseBadRequest("Missing Data")
        
        try: 
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing User")
        
        if data['action'] == "Follow":
            #follow
            follower, created = Followers.objects.get_or_create(
                followed_by = request.user, #this is the logged in user
                following = other_user
            )
        else: 
            #unfollow
            try: 
                follower = Followers.objects.get(
                    followed_by = request.user,
                    following = other_user
                )
            except Followers.DoesNotExist:
                follower = None
                
            if follower: 
                follower.delete()
        
        follower_size = Followers.objects.filter(following__username=other_user).count()
        following_size = Followers.objects.filter(followed_by = other_user).count()
        
        return JsonResponse({
            "done": "Success",
            "wording": "Unfollow" if data["action"] == "Follow" else "Follow",
            "followers": follower_size,
            "following": following_size,
        }) 
        
        
class EditProfile(LoginRequiredMixin, TemplateView): 
    http_method_names = ["get","post"]
    template_name = "profiles/edit_profile.html"

    def post(self, request, *args, **kwargs):
        profile_image = request.FILES.get("image")
        cover_image = request.FILES.get("cover_image")
        username = request.POST.get("username")
        first_name =  request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
     

        # Validate images
        if profile_image: 
            if not self.verify_image(profile_image):
                return JsonResponse({
                    'error': 'Invalid profile image. Only JPEG, PNG, and GIF files are allowed.'
                }, status=400)
            request.user.profile.image = profile_image

        if cover_image:    
            if not self.verify_image(cover_image):
                return JsonResponse({
                    'error': 'Invalid backdrop image. Only JPEG, PNG, and GIF files are allowed.'
                }, status=400)
            request.user.profile.backdrop_image = cover_image
                 
        # Update user profile and user details
        if username:
            exist = User.objects.filter(username=username).exists()
            if not exist:
                request.user.username = username
            else: 
                return JsonResponse({
                    'error': "username already exist. Try Again"
                }, status=400)
        if first_name: 
            request.user.first_name = first_name
        
        if last_name:
            request.user.last_name = last_name
        
        if email:
            exist = User.objects.filter(email=email).exists()
            if not exist:
                request.user.email = email
            else: 
                return JsonResponse({
                    'error': "email already exist. Try Again"
                }, status=400)
        
        logger.info("saving user profile.........")
        # Save the changes to the user
        try:
            request.user.save()
        # Update or set profile images
            request.user.profile.save()
        except Exception as e:
            logger.error("Error saving user profile ", str(e))
        # Redirect to the user's profile page
        redirect_url = reverse('profiles:detail', kwargs={'username': request.user.username})
        response_data = {'redirect': redirect_url}
        return JsonResponse(response_data)
        

    @staticmethod
    def verify_image(image_file):
        allowed_types = ['image/jpeg', 'image/png', 'image/gif']

        # Check the content type of the image
        if image_file.content_type not in allowed_types:
            return False

        return True

profiles/templates/profiles/details.html
{% extends 'base.html' %}

{% block title %} {{user.username}} profile {% endblock %}

{% block body %}
    <!-- component -->
    <div class="rounded-3xl overflow-hidden  shadow-xl lg:w-1/2 md:w-[70%] w-full my-12 mx-auto bg-white dark:bg-gray-900 relative">
        <div class="w-full h-48 bg-origin-padding bg-no-repeat bg-center bg-cover">
            <img src="{% if user.profile.backdrop_image %} {{user.profile.backdrop_image.url}} {% else %} https://i.imgur.com/dYcYQ7E.png {% endif %}" class="w-full h-full object-cover" />
        </div>
        <div class="flex justify-center -mt-8 mb-10 X">
            <img class="rounded-full border-solid w-40 h-40 border-teal-500 border-2 -mt-3 object-cover" src="{% if user.profile.image %}{{user.profile.image.url}}{% else %}https://i.imgur.com/dYcYQ7E.png{% endif %}" alt="avatar">
        </div>
        <div class="text-center px-3 pb-6 pt-2">
            <h3 class="text-black dark:text-white text-lg font-bold capitalize font-sans ">{{user.first_name}} {{user.last_name}}</h3>
            <div class=" text-sm capitalize font-sans p-3">
                <span class="block text-black dark:text-white">@{{user.username}}</span>
                <span class="block text-blue-600 dark:text-blue-300">{{user.email}}</span>
            </div>
            {% if request.user.is_authenticated %}
                {% if request.user != user %}
                    <button type="button" class="bg-black dark:bg-white text-gray-800 font-bold border-b-2 border-teal-500 hover:border-teal-600 hover:bg-teal-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center active:scale-[.97] text-sm my-6 js-follow edit-but" data-username="{{user.username}}" data-url= "{% url 'profiles:follow' user.username %}" data-action="{% if check_follow %}Unfollow{% else %}Follow{% endif %}">
                        <span class="mr-2 js-follow-text">
                            {% if check_follow %}Unfollow{% else %}Follow{% endif %}
                        </span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                        </svg>
                    </button>
                {% else %}
                    <a
                        href="{% url 'profiles:edit' user.username %}"
                        class="dark:bg-white text-gray-800 font-bold border-b-2 border-teal-500 hover:border-teal-600 hover:bg-teal-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center text-sm my-6 active:scale-[.97] edit-but">
                        <span class="mr-2">
                            Edit Profile
                        </span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 16 16" class="fillcurrent">
                            <g fill="currentcolor">
                            <path d="M5.002 10L12 3l2 2-7 7H5z" fill="currentcolor"/>
                            <path d="M1.094 0C.525 0 0 .503 0 1.063v13.874C0 15.498.525 16 1.094 16h10.812c.558 0 1.074-.485 1.094-1.031V8l-2 2v4H2V2h5l2 2 1.531-1.531L8.344.344A1.12 1.12 0 007.563 0z" style="line-height:normal;-inkscape-font-specification:Sans;text-indent:0;text-align:start;text-decoration-line:none;text-transform:none;marker:none" fill="currentcolor" font-weight="400" font-family="Sans" overflow="visible"/>
                            <path d="M14.19 1.011a.513.513 0 00-.364.152l-1.162 1.16 2.004 2.005 1.163-1.162a.514.514 0 000-.728l-1.277-1.275a.514.514 0 00-.364-.152z" style="isolation:auto;mix-blend-mode:normal;marker:none" fill="currentcolor" overflow="visible" fill-rule="evenodd"/>
                            </g>    
                        </svg>
                    </a>
                {% endif %}
            {% else %}
                <p class="my-6 text-sm text-black dark:text-white "><a href="{% url 'account_login' %}" class="text-blue-500"> Login</a> to Follow user</p>
            {% endif %}
        </div>

        <div class="flex justify-center pb-3 text-black dark:text-white">
            <div class="text-center mr-3 border-r pr-3 border-teal-500">
                <h2>{{ total_posts }}</h2>
                <span>Posts</span>
            </div>
            <div class="text-center mr-3 border-r pr-3 border-teal-500">
                <h2 class="followers">{{total_followers}}</h2>
                <span>Followers</span>
            </div>
            <div class="text-center">
                <h2 class="following">{{total_following}}</h2>
                <span>Following</span>
            </div>
        </div>
       
    </div>
    
{% endblock %}

profiles/templates/profiles/edit_profile.html
{% extends 'base.html' %}


{% block title %} {{user.username}} edit {% endblock %}

{% block body %}
    <!-- component -->
    <div class="rounded-3xl overflow-hidden shadow-xl lg:w-1/2 md:w-[70%] w-full my-12 mx-auto bg-white dark:bg-gray-900 relative">
        <div class="w-full h-48 bg-origin-padding bg-no-repeat bg-center bg-cover z-0 relative">
            <img src="{%if user.profile.backdrop_image %} {{user.profile.backdrop_image.url}} {% else %} https://i.imgur.com/dYcYQ7E.png {% endif %}" class="w-full h-full image-fluid object-cover" alt="cover image" id="cover_image_display">
            <div class="w-full h-full bg-black opacity-50 z-0 absolute top-0 left-0"></div>
            <div class=" absolute top-5 right-0">
                <label for="upload_cover_image" class="cursor-pointer flex flex-row justify-center items-center">
                    <span class="px-3 py-1 bg-white text-black dark:text-white dark:bg-black opacity-100 rounded-lg text-[15px] cursor-pointer active:scale-[.97]">change cover image
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 512 512" version="1.1" xml:space="preserve" class="inline"><g id="Layer_1"/><g id="Layer_2"><g> <g>
                            <path class="st0" fill="currentcolor" d="M307.81,212.18c-3.24,0-6.07-2.17-6.91-5.3l-4.82-17.88c-0.84-3.12-3.68-5.3-6.91-5.3h-21.46h-25.44H220.8     c-3.24,0-6.07,2.17-6.91,5.3l-4.82,17.88c-0.84,3.12-3.68,5.3-6.91,5.3H169.5c-3.96,0-7.16,3.21-7.16,7.16v101.78     c0,3.96,3.21,7.16,7.16,7.16h170.95c3.96,0,7.16-3.21,7.16-7.16V219.35c0-3.96-3.21-7.16-7.16-7.16H307.81z M282.33,264.94     c-0.86,13.64-11.93,24.71-25.58,25.58c-16.54,1.05-30.18-12.59-29.14-29.14c0.86-13.64,11.93-24.71,25.58-25.58     C269.74,234.76,283.38,248.4,282.33,264.94z"/>
                            </g><g>
                            <path class="st0" fill="currentcolor" d="M82.95,272.41c3.82,0,7.53-1.53,10.23-4.23l21.23-21.23c4.74-4.74,6.4-11.92,3.73-18.06     c-2.73-6.29-8.88-8.95-18.84-7.57l-0.27,0.27c15.78-71.56,79.7-125.27,155.94-125.27c60.72,0,115.41,33.72,142.73,87.99     c3.58,7.11,12.24,9.97,19.34,6.39c7.11-3.58,9.97-12.24,6.39-19.34c-15.47-30.73-39.05-56.66-68.22-75.01     C325.23,77.47,290.57,67.5,254.98,67.5c-93,0-170.48,67.71-185.75,156.41c-5.38-4.77-13.59-5.18-19.13-0.44     c-6.3,5.39-6.75,14.88-1.13,20.84c0.23,0.24,5.69,6.03,11.41,11.93c3.41,3.51,6.2,6.33,8.3,8.38c4.23,4.13,7.88,7.69,14.07,7.78     C82.81,272.41,82.88,272.41,82.95,272.41z"/></g><g>
                            <path class="st0" fill="currentcolor" d="M464.28,247.82l-26.5-26.5c-2.75-2.75-6.57-4.3-10.44-4.23c-2.33,0.03-4.29,0.56-6.07,1.42     c-0.26,0.12-0.51,0.26-0.76,0.4c-0.04,0.02-0.08,0.04-0.12,0.06c-0.59,0.33-1.16,0.68-1.69,1.08c-1.88,1.34-3.6,3.03-5.44,4.82     c-2.1,2.05-4.89,4.87-8.3,8.38c-5.72,5.9-11.18,11.68-11.41,11.93c-5.46,5.79-5.19,14.91,0.6,20.36     c5.75,5.42,14.77,5.18,20.24-0.48c-4.72,83.85-74.42,150.62-159.43,150.62c-70.52,0-131.86-45.23-152.62-112.55     c-2.35-7.6-10.41-11.86-18.01-9.52c-7.6,2.34-11.86,10.41-9.52,18.01c11.62,37.68,35.48,71.52,67.19,95.28     c32.8,24.59,71.86,37.58,112.96,37.58c100.11,0,182.23-78.45,188.14-177.1l0.79,0.79c2.81,2.81,6.5,4.22,10.18,4.22     c3.69,0,7.37-1.41,10.18-4.22C469.91,262.57,469.91,253.45,464.28,247.82z"/></g></g></g>
                        </svg>
                    </span>
                </label>
                <input id="upload_cover_image" type="file" class="hidden" onchange="previewImage(this, '#cover_image_display')" accept="image/*" />
            </div>
        </div>
        <div class="flex justify-center relative -mt-8 z-10 ">
            <div class="relative rounded-full w-40 h-40 border-solid border-teal-500 border-4">
                {%if user.profile.image %}
                    <img class="rounded-full absolute top-0 left-0 w-full h-full" src="{{user.profile.image.url}}" alt="avatar" id="profile_img_display" >
                {% else %}  
                    <img class="rounded-full absolute top-0 left-0 w-full h-full" src=" https://i.imgur.com/dYcYQ7E.png" alt="avatar" id="profile_img_display">
                
                {% endif %}
                <div class="absolute bg-black opacity-50 rounded-full w-full h-full top-0 left-0">
                </div>
                
                <div class=" absolute top-[88px] right-[-10px] ">
                    <label for="upload_profile_image" class="cursor-pointer flex flex-row justify-center items-center">
                        <span class="px-3 py-1 bg-white text-black dark:text-white dark:bg-gray-900 opacity-100 rounded-lg text-[11px] cursor-pointer active:scale-[.97]">change 
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 512 512" version="1.1" xml:space="preserve" class="inline"><g id="Layer_1"/>
                                <g id="Layer_2">
                                    <g> 
                                        <g>
                                            <path class="st0" fill="currentcolor" d="M307.81,212.18c-3.24,0-6.07-2.17-6.91-5.3l-4.82-17.88c-0.84-3.12-3.68-5.3-6.91-5.3h-21.46h-25.44H220.8     c-3.24,0-6.07,2.17-6.91,5.3l-4.82,17.88c-0.84,3.12-3.68,5.3-6.91,5.3H169.5c-3.96,0-7.16,3.21-7.16,7.16v101.78     c0,3.96,3.21,7.16,7.16,7.16h170.95c3.96,0,7.16-3.21,7.16-7.16V219.35c0-3.96-3.21-7.16-7.16-7.16H307.81z M282.33,264.94     c-0.86,13.64-11.93,24.71-25.58,25.58c-16.54,1.05-30.18-12.59-29.14-29.14c0.86-13.64,11.93-24.71,25.58-25.58     C269.74,234.76,283.38,248.4,282.33,264.94z"/>
                                        </g>
                                        <g>
                                            <path class="st0" fill="currentcolor" d="M82.95,272.41c3.82,0,7.53-1.53,10.23-4.23l21.23-21.23c4.74-4.74,6.4-11.92,3.73-18.06     c-2.73-6.29-8.88-8.95-18.84-7.57l-0.27,0.27c15.78-71.56,79.7-125.27,155.94-125.27c60.72,0,115.41,33.72,142.73,87.99     c3.58,7.11,12.24,9.97,19.34,6.39c7.11-3.58,9.97-12.24,6.39-19.34c-15.47-30.73-39.05-56.66-68.22-75.01     C325.23,77.47,290.57,67.5,254.98,67.5c-93,0-170.48,67.71-185.75,156.41c-5.38-4.77-13.59-5.18-19.13-0.44     c-6.3,5.39-6.75,14.88-1.13,20.84c0.23,0.24,5.69,6.03,11.41,11.93c3.41,3.51,6.2,6.33,8.3,8.38c4.23,4.13,7.88,7.69,14.07,7.78     C82.81,272.41,82.88,272.41,82.95,272.41z"/>
                                        </g>
                                        <g>
                                            <path class="st0" fill="currentcolor" d="M464.28,247.82l-26.5-26.5c-2.75-2.75-6.57-4.3-10.44-4.23c-2.33,0.03-4.29,0.56-6.07,1.42     c-0.26,0.12-0.51,0.26-0.76,0.4c-0.04,0.02-0.08,0.04-0.12,0.06c-0.59,0.33-1.16,0.68-1.69,1.08c-1.88,1.34-3.6,3.03-5.44,4.82     c-2.1,2.05-4.89,4.87-8.3,8.38c-5.72,5.9-11.18,11.68-11.41,11.93c-5.46,5.79-5.19,14.91,0.6,20.36     c5.75,5.42,14.77,5.18,20.24-0.48c-4.72,83.85-74.42,150.62-159.43,150.62c-70.52,0-131.86-45.23-152.62-112.55     c-2.35-7.6-10.41-11.86-18.01-9.52c-7.6,2.34-11.86,10.41-9.52,18.01c11.62,37.68,35.48,71.52,67.19,95.28     c32.8,24.59,71.86,37.58,112.96,37.58c100.11,0,182.23-78.45,188.14-177.1l0.79,0.79c2.81,2.81,6.5,4.22,10.18,4.22     c3.69,0,7.37-1.41,10.18-4.22C469.91,262.57,469.91,253.45,464.28,247.82z"/>
                                        </g>
                                    </g>
                                </g>
                            </svg>
                        </span>
                    </label>
                    <input id="upload_profile_image" type="file" class="hidden" onchange="previewImage(this, '#profile_img_display')" accept="image/*" />
                </div>
            </div>
        </div>

        <h2 class="text-2xl font-semibold text-black text-center dark:text-white mt-4">Edit Profile</h2>
        <p id="error-text" class="text-md text-red-500 text-center mt-5 p-3 font-bold"></p>
        <div class="space-y-1" data-url="{% url 'profiles:edit' user.username %}" id="edit-form">
                <div class="shadow-xl p-10 flex flex-col gap-2 text-sm text-gray-600 dark:text-white">
                <div>
                    <label class="font-bold inline-block pb-2" for="username">Username</label>
                    <input class="border text-gray-600 border-gray-400 focus:outline-slate-400 rounded-md w-full shadow-sm px-5 py-2" pattern="^[a-zA-Z0-9_.-]+$" type="text" id="username" title="Only letters, numbers, underscores, periods, and hyphens are allowed." placeholder="{{user.username}} (change optional)">
                </div>
                <div>
                    <label class="font-bold inline-block pb-2" for="first_name">First Name</label>
                    <input class="border text-gray-600 border-gray-400 focus:outline-slate-400 rounded-md w-full shadow-sm px-5 py-2" type="text" id="first_name" placeholder="{{user.first_name}} (change optional)" >
                </div>
                <div>
                    <label class="font-bold inline-block pb-2" for="last_name">Last Name</label>
                    <input class="border text-gray-600 border-gray-400 focus:outline-slate-400 rounded-md w-full shadow-sm px-5 py-2" type="text" id="last_name" placeholder="{{user.last_name}} (change optional)" >
                </div>
                <div>
                    <label class="font-bold inline-block pb-2" for="email">Email</label>
                    <input class="border text-gray-600 border-gray-400 focus:outline-slate-400 rounded-md w-full shadow-sm px-5 py-2" type="email" id="email"  placeholder="{{user.email}} (change optional)" >
                </div>
                <div>
                        <a class="font-bold text-blue-600" href="">Change password?</a>
                </div>
                <div>
                    <input class="bg-[#4F46E5] w-full py-2 rounded-md text-white font-bold cursor-pointer hover:bg-[#181196]" type="submit" value="Save" id="js-save-edit" >
                </div>
            </div>  
        </div> 
    </div>
    
{% endblock %}