nk_social_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    re_path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

posts/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.HopePage.as_view(), name="index"),
    path("following/", views.FollowingView.as_view(), name="following"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from cloudinary.models import CloudinaryField

# Create your models here.
class Post(models.Model) : 
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now_add=True)
    # image = ImageField(upload_to='post_images/', null=True, blank=True)
    image = CloudinaryField('image')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    
    def __str__(self):
        return self.text[0:30]

posts/views.py
from typing import Any
from django.views.generic import TemplateView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from .models import Post
from followers.models import Followers
from django.http import JsonResponse

# Create your views here.
class HopePage(LoginRequiredMixin, TemplateView) : 
    http_method_names = ["get"]
    template_name = "homepage.html"
    
    def dispatch (self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        
        if self.request.user.is_authenticated: 
            posts = Post.objects.all().order_by("-id")[0:30] 
            context["posts"] = posts
        
        return context
    
    
class FollowingView(LoginRequiredMixin, TemplateView):
    http_method_names = ["get"]
    template_name = "following.html"
    
    def dispatch (self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        
        if self.request.user.is_authenticated:
            follower = list(Followers.objects.filter(followed_by=self.request.user).values_list("following", flat=True))
            if follower:
                posts = Post.objects.filter(author__in=follower).order_by("-id")[0:60]
            else: 
                posts = Post.objects.filter(author=self.request.user).order_by("-id")[0:30]
            
            context["posts"] = posts
        return context
    
    
class PostDetailView(DetailView):
    http_method_names = ['get']
    template_name = "detail.html"
    model = Post
    context_object_name = 'post'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"].text_shortened = context['post'].text[:14]
        return context
    
class CreateNewPost(LoginRequiredMixin, CreateView): 
    model = Post
    template_name = "create.html"
    fields = ['text']
    success_url= "/"
    
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save() 
        return super().form_valid(form)
    
    
    def post(self, request, *args, **kwargs):
        
        images = request.FILES.get("image"),
        
        for image in images:
        # Check if an image is provided
            if image:
                allowed_types = ['image/jpeg', 'image/png', 'image/gif']

                # Check the content type of the image
                if image.content_type not in allowed_types:
                    return JsonResponse({
                        'error': 'Invalid file format. Only image files (JPEG, PNG, GIF) are allowed.'
                    }, status=400)

        # Create a new Post with the image
        post = Post.objects.create(
            text=request.POST.get("post"),
            image=image,
            author=request.user,
        )
        
        return render(
            request,
            "includes/post.html",
            {
                "post": post,
                "show_link": True
            },
            content_type = "application/html"
        )

nk_social_app/templates/includes/post.html


<!-- component -->
<!-- class="flex items-center xs:w-[85%] shadow-xl w-full sm:w-[60%] mx-auto bg-white my-20 md:my-0 dark:bg-gray-900 rounded-3xl" -->
<div class="post-detail w-[90%] bg-white shadow-lg dark:bg-gray-800 dark:border-gray-800 p-4 py-5 px-5 my-10 rounded-xl border mx-auto overflow-hidden" data-url="{% url 'post:detail' post.id %}" data-show="{{show_link}}">
    <div class="flex justify-between">
        <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
            <img class="h-11 w-11 rounded-full object-cover" src="{{post.author.profile.image.url}}"/>
            <div class="ml-1.5 text-sm leading-tight">
                <span class="text-black dark:text-white font-bold block ">{{post.author.username}}</span>
                <span class="text-gray-500 dark:text-gray-400 font-normal block">@{{post.author.username}}</span>
            </div>
        </a>
        <svg class="text-blue-400 dark:text-white h-6 w-auto inline-block fill-current" viewBox="0 0 24 24">
            <g>
                <path d="M23.643 4.937c-.835.37-1.732.62-2.675.733.962-.576 1.7-1.49 2.048-2.578-.9.534-1.897.922-2.958 1.13-.85-.904-2.06-1.47-3.4-1.47-2.572 0-4.658 2.086-4.658 4.66 0 .364.042.718.12 1.06-3.873-.195-7.304-2.05-9.602-4.868-.4.69-.63 1.49-.63 2.342 0 1.616.823 3.043 2.072 3.878-.764-.025-1.482-.234-2.11-.583v.06c0 2.257 1.605 4.14 3.737 4.568-.392.106-.803.162-1.227.162-.3 0-.593-.028-.877-.082.593 1.85 2.313 3.198 4.352 3.234-1.595 1.25-3.604 1.995-5.786 1.995-.376 0-.747-.022-1.112-.065 2.062 1.323 4.51 2.093 7.14 2.093 8.57 0 13.255-7.098 13.255-13.254 0-.2-.005-.402-.014-.602.91-.658 1.7-1.477 2.323-2.41z">                    
                </path>
            </g>
        </svg>
    </div>
    <div class="border-gray-200 dark:border-gray-600 border border-b-0 my-2"></div>
    <p class="text-black dark:text-white block text-xl leading-snug my-6 break-words">{{post.text}}</p>
    <div>
        {% if post.image %}
                <img class="my-4 rounded-2xl border w-full h-auto border-gray-100 shadow-md dark:border-gray-700 object-cover" src="{{post.image.url}}" alt="post-image">
        {% endif %}
    </div>
    <div class="border-gray-200 dark:border-gray-600 border border-b-0 my-1"></div>
    <p class="text-gray-500 dark:text-gray-400 text-base py-1 my-4">{{post.date|date:"F j, Y, g:i a" }}</p>
</div>

nk_social_app/templates/includes/post_view.html
<div class="flex flex-col">
    <div class="flex dark:text-gray-300 text-center text-md md:text-lg w-full bg-white dark:bg-black ">
        <a href="/" class="nav-link flex-grow hover:text-teal-400 hover:border-teal-500 p-5">All Posts</a>
        <a href="{% url 'post:following' %}" class="nav-link flex-grow hover:text-teal-400 hover:border-teal-500  p-5">Following</a>
    </div>
    <div class="post-container">
        {% for post in posts %}
            {% include 'includes/post.html' with post=post show_link=True %}
        {% endfor%}
    </div>
</div>